version: '2'
services:
  web:
    build: .
    command: npm run dev
    volumes:
      - .:/usr/app/
    ports:
      - 3001:3001
      - 3000:3000
      - 8080:8080
    depends_on:
      - mongodb
    environment:
      MONGO_URL: mongodb://mongodb:27017/post-website-dev
  mongodb:
    ports:
      - 27017:27017
    image: mongo